### ISSUE TITLE
Model can't be serialized: self.thisptr cannot be converted to a Python object for pickling

### ISSUE THREAD

**Issue by repko-artem** [bluesheeptoken/subseq#10]
Hi!
First of all thank you for this package - model produces great results.
But we faced with problem that the model can't be saved. We can't neither pickle nor dill it as it has non-serializable object 'thisptr'.
Example:
```
from dill import dumps
from subseq.subseq import Subseq

model = Subseq(1)
model.fit([['hello', 'world']])
dumps(model)
```
execs with exception
```
  File "<input>", line 1, in <module>
  File "\lib\site-packages\dill\_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "\lib\site-packages\dill\_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "\lib\site-packages\dill\_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "stringsource", line 2, in subseq.subseq.Subseq.__reduce_cython__
TypeError: self.thisptr cannot be converted to a Python object for pickling
```

Do you have any solution how to store the resulting model in storage?

**Comment by bluesheeptoken** [comment]
Hello,
Thanks for the feedback, I appreciate !

Tbh, I did not implement this feature yet because noone needed it so far.

Regarding the exceptions, I highly suspect Cython to not generate all objects as Python objects. Hence we will need to create a `__reduce__` method or `__setstate__` and `__getstate__` methods. (This has been done here: https://github.com/bluesheeptoken/CPT/search?q=pickle&type=commits)

Does `dill` relies on the same magic methods to serialize an object?

I will try to give it a shot soon and keep you up to date !

**Comment by repko-artem** [comment]
Hi!
Thank you for superfast response!
I think so - as callstack with exception contains this method. In any case it's important to save the model - no difference with pickle or with dill.
Looking forward for update.

**Comment by sebastian-ho** [comment]
Hi! I faced the same issue too, and I found this discussion here. Hopefully this can be implemented soon. Looking forward for the update as well :)

**Comment by bluesheeptoken** [comment]
Won't have time to finish this week, but I started already #11

Only the interface with Python left

**Comment by bluesheeptoken** [comment]
Hi again !
Sorry for the delay, I was quite busy recently. And I also wanted to try new things, hence the delay.

This is now [released](https://pypi.org/project/subseq/) 🥳 for python >= V3.7, it works with [`pickle`](https://github.com/bluesheeptoken/subseq/blob/master/tests/test_subseq.py#L23-L28). (I Haven't tried with `dill` tbh)

Could you confirm it works for both of you?

Do not hesitate to star the project. It encourages me maintaining it :)

**Comment by repko-artem** [comment]
Hi!
It works for both. Thanks a lot! You're great!
