### ISSUE TITLE
installation error on linux

### ISSUE THREAD

**Issue by localcreator** [bluesheeptoken/subseq#19]
Hi! In fedora 38 and Ubuntu 23.04, an error occurs when installing the package
Python 3.11.2
![Снимок экрана от 2023-06-04 01-19-04](https://github.com/bluesheeptoken/subseq/assets/76257407/64b266aa-7e0b-4b0e-9f53-3b461564ebc2)
P.s. It looks like the problem is due to Python 3.11, in Python 3.10 on the same operating systems, the installation goes without problems.

**Comment by bluesheeptoken** [comment]
Hello,
Well caught, I thought I published the 3.11 version, but I just checked. And apparently I did not.

I will try to publish soon a new version with a `proba` method. This will also push the 3.11 version

Is that fine for you to use the 3.10 meanwhile?

**Comment by localcreator** [comment]
Yes, so far I'm doing it

**Comment by bluesheeptoken** [comment]
Version 1.0.4, now contains a wheel for python 3.11 :tada:

**Comment by localcreator** [comment]
Installed on Python 3.11 without problems.
