### ISSUE TITLE
predict_k feature with subseq

### ISSUE THREAD

**Issue by AlexVielfaure** [bluesheeptoken/subseq#6]
Hi, 
Thanks for this package. I was wondering if there was an option to access the top k predictions or least get the probabilities. 
thanks !

**Comment by bluesheeptoken** [comment]
Hi,
Sorry for the delay. I don't know why I did not receive the notification.
Currently we cannot get the best k predictions. However, the development does not seem to be difficult.
You can give it a shot (I am here to help), or I will try to find some time to do it (this week is not feasible for me, I can try next week)

You can have a look at the CPT project which is a bit similar and the `predict_k` feature has already been asked and implemented

**Comment by bluesheeptoken** [comment]
For reference: [predict_k CPT](https://github.com/bluesheeptoken/CPT/commit/13d6c89973b35bc863ee1d457d1e4f4c2ccfda75)
As both algorithms maintain an array of scores per candidate, the implementation is probably similar

**Comment by bluesheeptoken** [comment]
I just released [`subseq==1.0.1`](https://pypi.org/project/subseq/). This release adds the `predict_k` method. Do not hesitate to have a try.

If that does not help you, do not hesitate to reopen the ticket

**Comment by repko-artem** [comment]
Thank you for quick response.
Unfortunately, I'm too bad in C++ to resolve the issue. I will try my skills later if you don't have time. Currently I just exclude such items from result of the method.

**Comment by bluesheeptoken** [comment]
Alright, makes complete sense :)
I will try to find time doing it this week-end (with some luck, pcodingame won't take too much of my time)

**Comment by bluesheeptoken** [comment]
Hi @repko-artem, I just pushed a V1.0.3 version where we don't return the mysterious, internal implementation, `$`.

Feel free to upgrade and give me feedback 🥳
